//prettier-ignore
export const cryptocurrencyList = [
  { name: 'Bitcoin', symbol: 'BTC', logo: 'https://cryptologos.cc/logos/bitcoin-btc-logo.png' },
  { name: 'Ethereum', symbol: 'ETH', logo: 'https://cryptologos.cc/logos/ethereum-eth-logo.png' },
  { name: 'Ripple', symbol: 'XRP', logo: 'https://cryptologos.cc/logos/xrp-xrp-logo.png' },
  { name: 'Litecoin', symbol: 'LTC', logo: 'https://cryptologos.cc/logos/litecoin-ltc-logo.png' },
  { name: 'Bitcoin Cash', symbol: 'BCH', logo: 'https://cryptologos.cc/logos/bitcoin-cash-bch-logo.png' },
  { name: 'Cardano', symbol: 'ADA', logo: 'https://cryptologos.cc/logos/cardano-ada-logo.png' },
  { name: 'Polkadot', symbol: 'DOT', logo: 'https://cryptologos.cc/logos/polkadot-new-dot-logo.png' },
  { name: 'Binance Coin', symbol: 'BNB', logo: 'https://cryptologos.cc/logos/binance-coin-bnb-logo.png' },
  { name: 'Chainlink', symbol: 'LINK', logo: 'https://cryptologos.cc/logos/chainlink-link-logo.png' },
  { name: 'Stellar', symbol: 'XLM', logo: 'https://cryptologos.cc/logos/stellar-xlm-logo.png' },
  { name: 'USD Coin', symbol: 'USDC', logo: 'https://cryptologos.cc/logos/usd-coin-usdc-logo.png' },
  { name: 'Dogecoin', symbol: 'DOGE', logo: 'https://cryptologos.cc/logos/dogecoin-doge-logo.png' },
  { name: 'Wrapped Bitcoin', symbol: 'WBTC', logo: 'https://cryptologos.cc/logos/wrapped-bitcoin-wbtc-logo.png' },
  { name: 'Avalanche', symbol: 'AVAX', logo: 'https://cryptologos.cc/logos/avalanche-avax-logo.png' },
  { name: 'Filecoin', symbol: 'FIL', logo: 'https://cryptologos.cc/logos/filecoin-fil-logo.png' },
  { name: 'Bitcoin SV', symbol: 'BSV', logo: 'https://cryptologos.cc/logos/bitcoin-sv-bsv-logo.png' },
  { name: 'TRON', symbol: 'TRX', logo: 'https://cryptologos.cc/logos/tron-trx-logo.png' },
  { name: 'Monero', symbol: 'XMR', logo: 'https://cryptologos.cc/logos/monero-xmr-logo.png' },
  { name: 'EOS', symbol: 'EOS', logo: 'https://cryptologos.cc/logos/eos-eos-logo.png' },
  { name: 'Tether', symbol: 'USDT', logo: 'https://cryptologos.cc/logos/tether-usdt-logo.png' },
  { name: 'Cosmos', symbol: 'ATOM', logo: 'https://cryptologos.cc/logos/cosmos-atom-logo.png' },
  { name: 'Tezos', symbol: 'XTZ', logo: 'https://cryptologos.cc/logos/tezos-xtz-logo.png' },
  { name: 'IOTA', symbol: 'MIOTA', logo: 'https://cryptologos.cc/logos/iota-miota-logo.png' },
  { name: 'Theta', symbol: 'THETA', logo: 'https://cryptologos.cc/logos/theta-theta-logo.png' },
  { name: 'VeChain', symbol: 'VET', logo: 'https://cryptologos.cc/logos/vechain-vet-logo.png' },
  { name: 'UNUS SED LEO', symbol: 'LEO', logo: 'https://cryptologos.cc/logos/unus-sed-leo-leo-logo.png' },
  { name: 'Neo', symbol: 'NEO', logo: 'https://cryptologos.cc/logos/neo-neo-logo.png' },
  { name: 'Maker', symbol: 'MKR', logo: 'https://cryptologos.cc/logos/maker-mkr-logo.png' },
  { name: 'Dai', symbol: 'DAI', logo: 'https://cryptologos.cc/logos/dai-dai-logo.png' },
  { name: 'Compound', symbol: 'COMP', logo: 'https://cryptologos.cc/logos/compound-comp-logo.png' },
  { name: 'Synthetix', symbol: 'SNX', logo: 'https://cryptologos.cc/logos/synthetix-network-token-snx-logo.png' },
  { name: 'Aave', symbol: 'AAVE', logo: 'https://cryptologos.cc/logos/aave-aave-logo.png' },
  { name: 'Dash', symbol: 'DASH', logo: 'https://cryptologos.cc/logos/dash-dash-logo.png' },
  { name: 'The Graph', symbol: 'GRT', logo: 'https://cryptologos.cc/logos/the-graph-grt-logo.png' },
  { name: 'Decred', symbol: 'DCR', logo: 'https://cryptologos.cc/logos/decred-dcr-logo.png' },
  { name: 'Huobi Token', symbol: 'HT', logo: 'https://cryptologos.cc/logos/huobi-token-ht-logo.png' },
  { name: 'Compound', symbol: 'COMP', logo: 'https://cryptologos.cc/logos/compound-comp-logo.png' },
  { name: 'SushiSwap', symbol: 'SUSHI', logo: 'https://cryptologos.cc/logos/sushiswap-sushi-logo.png' },
  { name: 'Yearn.finance', symbol: 'YFI', logo: 'https://cryptologos.cc/logos/yearn-finance-yfi-logo.png' },
  { name: 'Zcash', symbol: 'ZEC', logo: 'https://cryptologos.cc/logos/zcash-zec-logo.png' },
  { name: 'Qtum', symbol: 'QTUM', logo: 'https://cryptologos.cc/logos/qtum-qtum-logo.png' },
  { name: 'THORChain', symbol: 'RUNE', logo: 'https://cryptologos.cc/logos/thorchain-rune-logo.png' },
  { name: 'Curve DAO Token', symbol: 'CRV', logo: 'https://cryptologos.cc/logos/curve-dao-token-crv-logo.png' },
  { name: 'Kusama', symbol: 'KSM', logo: 'https://cryptologos.cc/logos/kusama-ksm-logo.png' },
  { name: 'Bitcoin Gold', symbol: 'BTG', logo: 'https://cryptologos.cc/logos/bitcoin-gold-btg-logo.png' },
  { name: 'NEM', symbol: 'XEM', logo: 'https://cryptologos.cc/logos/nem-xem-logo.png' },
  { name: 'Horizen', symbol: 'ZEN', logo: 'https://cryptologos.cc/logos/horizen-zen-logo.png' },
  { name: 'ICON', symbol: 'ICX', logo: 'https://cryptologos.cc/logos/icon-icx-logo.png' },
  { name: 'OMG Network', symbol: 'OMG', logo: 'https://cryptologos.cc/logos/omg-network-omg-logo.png' },
  { name: 'Harmony', symbol: 'ONE', logo: 'https://cryptologos.cc/logos/harmony-one-logo.png' },
  { name: 'Celsius', symbol: 'CEL', logo: 'https://cryptologos.cc/logos/celsius-cel-logo.png' },
  { name: 'Hedera Hashgraph', symbol: 'HBAR', logo: 'https://cryptologos.cc/logos/hedera-hashgraph-hbar-logo.png' },
  { name: 'SwissBorg', symbol: 'CHSB', logo: 'https://cryptologos.cc/logos/swissborg-chsb-logo.png' },
  { name: 'OKB', symbol: 'OKB', logo: 'https://cryptologos.cc/logos/okb-okb-logo.png' },
  { name: 'Elrond', symbol: 'EGLD', logo: 'https://cryptologos.cc/logos/elrond-egld-logo.png' },
  { name: 'Ontology', symbol: 'ONT', logo: 'https://cryptologos.cc/logos/ontology-ont-logo.png' },
  { name: 'Algorand', symbol: 'ALGO', logo: 'https://cryptologos.cc/logos/algorand-algo-logo.png' },
  { name: 'Waves', symbol: 'WAVES', logo: 'https://cryptologos.cc/logos/waves-waves-logo.png' },
  { name: 'Nano', symbol: 'NANO', logo: 'https://cryptologos.cc/logos/nano-nano-logo.png' },
  { name: 'IOST', symbol: 'IOST', logo: 'https://cryptologos.cc/logos/iost-iost-logo.png' },
  { name: 'Decentraland', symbol: 'MANA', logo: 'https://cryptologos.cc/logos/decentraland-mana-logo.png' },
  { name: 'Ren', symbol: 'REN', logo: 'https://cryptologos.cc/logos/ren-ren-logo.png' },
];
